# build postgres

version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nest
    networks:
      - testtest

networks:
  testtest:
